CREATE TABLE Users(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  FIRST_NAME VARCHAR(64),
  LAST_NAME VARCHAR(64),
  EMAIL_ADDRESS VARCHAR(64)
);

CREATE TABLE Items(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  ITEM_NAME VARCHAR(64),
  ITEM_CATEGORY VARCHAR(64),
  CODE VARCHAR(64),
  COST INTEGER
);

CREATE TABLE Categories(
  ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  CATEGORY_NAME VARCHAR(64)
);
